### PR TITLE
Add support for node 10

### PR DESCRIPTION
**Pull request by glib-briia**
Add node 10 to appveyor build matrix

### CODE REVIEW

**Comment by glib-briia** [comment]
@MatthD , @trollkotze , could you please take  a look and merge this one. Appveyor build passing but failing on uploading release as It has to me @MatthD who trigger the build.

Thanks in advance.

**Comment by glib-briia** [comment]
Fixes #3

**Comment by glib-briia** [comment]
Hi @MatthD , @trollkotze it looks like you are not actively supporting this project any more. Would you be able to merge the PR or add me as contributor? really need v 10 support.

**Comment by MatthD** [comment]
Hi @glib-briia thank you very much for this PR , I will add you as contributor to be able to maintain it too.

**Comment by MatthD** [comment]
It's ok for me @glib-briia

**Pull request merged**
