### PR TITLE
ci: Add node 12 support

### PR DESCRIPTION
**Pull request by villelahdenvuo**

### CODE REVIEW

**Comment by villelahdenvuo** [comment]
We could probably already drop Node 4 and 6 support since they are EoL already.

**Comment by MatthD** [comment]
Hi @villelahdenvuo thanks for you contribution 😊, this seems a great & helpful PR, 

I think if we drop support for 4 & 6 / windows (your pr does not success for appveyor in 12) it will be cool create a major release & add it to the documentation.

Possible for you ?

**Comment by villelahdenvuo** [comment]
Hey,

I can do that. I'm currently looking into the build issue, seems like V8 has removed some deprecated stuff so the build fails. If I can get it to work we can do that.

**Comment by villelahdenvuo** [comment]
Hey @MatthD I managed to get the build go through and it seems to work okay, but I have an issue when running the tests, it just crashes:

```
  Node-Libxml
    ✓ Should return a list of errored path if dtd path is bad
dyld: lazy symbol binding failed: Symbol not found: __ZN6Libxml7ToCharsEN2v85LocalINS0_5ValueEEE
  Referenced from: /Users/ville/repos/node-libxml/build/Release/xml.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN6Libxml7ToCharsEN2v85LocalINS0_5ValueEEE
  Referenced from: /Users/ville/repos/node-libxml/build/Release/xml.node
  Expected in: flat namespace

[1]    49692 abort      npx mocha
```

I tried to Google the issue, but I didn't find much. Other than V8 has changed things and broke it. I found this PR of switching from nan to napi, but I don't know if I have enough time/skills to do that kind of refactoring myself: https://github.com/argv-minus-one/node-alias/commit/1672a5dcaf87cad887ca31018998d394d25da24f

**Comment by MatthD** [comment]
Thanks for your investigation @villelahdenvuo I will not have time to check this but I saw your PR has successfully built for v10/v12 Linux/Mac 👌, I think this could be a base for a new major version with an updated doc, you can publish it.
I can share you the npm repo too to publish this major.

**Pull request closed without merging**
